name: ADF-CI-CD

# Manual trigger with parameters
on:
  workflow_dispatch:
    inputs:
      # Name of the ADF Azure Resource
      ADF_NAME:
        description: 'ADF Name'
        required: true
        default: 'ADF-MyADFProject-{REPLACE-ME e.g. Feature-A-QA}'

      # This will Dev, QA and Prod appended
      ADF_PUBLISH_FOLDER:
        description: 'ADF Publish Folder Name in Git'
        required: true
        default: 'ADF-MyADFProject-{REPLACE-ME e.g. Feature-A}'

      # This resource group for the ADF
      RESOURCE_GROUP:
        description: 'Resource Group Name'
        required: true
        default: 'ADF-MyADFProject'

      # The Azure region to which to deploy your resources
      LOCATION:
        description: 'Azure Region'
        required: true
        default: 'SouthCentralUS'

      # For running PowerShell and creating resources
      SUBSCRIPTION_ID:
        description: 'Azure Subscription Id'
        required: true
        default: '00000000-0000-0000-0000-000000000000'

jobs:
  #############################################################
  # Builds the code
  # This is packaging up the files from Git to the Artifacts files
  #############################################################
  Build:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # Show paths
    - name: Show paths
      run: ls -R

    # Show the environment variables for debugging
    - name: Display Environment Variable
      uses: azure/powershell@v1
      with:
        inlineScript: |
          dir env:
        azPSVersion: '3.1.0'

    # Publish Artifact: Publish: ARM-Templates
    - name: 'Publish Artifact: ARM-Templates' 
      uses: actions/upload-artifact@v2
      with:
        name: 'ARM-Templates'
        path: '${{ github.workspace }}/ARM-Templates'

    # Publish Artifact: Publish: PowerShell-Scripts
    - name: 'Publish Artifact: PowerShell-Scripts' 
      uses: actions/upload-artifact@v2
      with:
        name: 'PowerShell-Scripts'
        path: '${{ github.workspace }}/PowerShell-Scripts'

    - name: Checkout adf_publish branch
      uses: actions/checkout@v2
      with:
        ref: adf_publish

    # Show paths
    - name: Show paths
      run: ls -R

    # Publish Artifact: adf_publish files
    - name: 'Publish Artifact: adf_publish' 
      uses: actions/upload-artifact@v2
      with:
        name: 'ADF-Publish-Dev'
        path: '${{ github.workspace }}/${{ github.event.inputs.ADF_PUBLISH_FOLDER }}'
