name: ADF-CI-CD

# Manual trigger with parameters
on:
  workflow_dispatch:
    inputs:
      # Name of the ADF Azure Resource
      # This will Dev, QA and Prod appended
      ADF_NAME:
        description: 'ADF Name'
        required: true
        default: 'ADF-MyADFProject'

      # This will Dev, QA and Prod appended
      # ADF_PUBLISH_FOLDER:
      #  description: 'ADF Publish Folder Name in Git'
      #  required: true
      #  default: 'ADF-MyADFProject'

      # This resource group for the ADF
      RESOURCE_GROUP:
        description: 'Resource Group Name'
        required: true
        default: 'ADF-MyADFProject'

      # The Azure region to which to deploy your resources
      LOCATION:
        description: 'Azure Region'
        required: true
        default: 'SouthCentralUS'

      # ???
      SUBSCRIPTION_ID:
        description: 'Azure Subscription Id'
        required: true
        default: '00000000-0000-0000-0000-000000000000'

jobs:
  #############################################################
  # Builds the code
  # This is packaging up the files from Git to the Artifacts files
  #############################################################
  Build:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Show the environment variables for debugging
    - name: Display Environment Variable
      uses: azure/powershell@v1
      with:
        inlineScript: |
          dir env:
        azPSVersion: '3.1.0'

    # Publish Artifact: Publish: ARM-Templates
    - name: 'Publish Artifact: ARM-Templates' 
      uses: actions/upload-artifact@v2
      with:
        name: 'ARM-Templates'
        path: '${{ github.workspace }}/ARM-Templates'

    # Publish Artifact: Publish: PowerShell-Scripts
    - name: 'Publish Artifact: PowerShell-Scripts' 
      uses: actions/upload-artifact@v2
      with:
        name: 'PowerShell-Scripts'
        path: '${{ github.workspace }}/PowerShell-Scripts'

    # Change branches
    - name: Change branches to adf_publish
      run: git checkout adf_publish

    # Publish Artifact: adf_publish files
    - name: 'Publish Artifact: adf_publish Files (Dev)' 
      uses: actions/upload-artifact@v2
      with:
        name: 'Publish-Files'
        path: '${{ github.workspace }}/${{ github.ADF_NAME }}-Dev'

    # Publish Artifact: adf_publish files
    - name: 'Publish Artifact: adf_publish Files (QA)' 
      uses: actions/upload-artifact@v2
      with:
        name: 'Publish-Files'
        path: '${{ github.workspace }}/${{ github.ADF_NAME }}-QA'

    # Publish Artifact: adf_publish files
    - name: 'Publish Artifact: adf_publish Files (Prod)' 
      uses: actions/upload-artifact@v2
      with:
        name: 'Publish-Files'
        path: '${{ github.workspace }}/${{ github.ADF_NAME }}-Prod'        