name: ADF-CI-CD

# Manual trigger with parameters
on:
  workflow_dispatch:
    inputs:
      # Name of your Azure ADF
      ADF_NAME:
        description: 'ADF Name to Deploy'
        required: true
        default: 'ADF-MyADFProject-{REPLACE-ME e.g. Feature-A}'

      # Name of the publish folder under adf_publish bnrach
      ADF_PUBLISH_FOLDER:
        description: 'ADF Publish Folder Name in Git (under adf_publish branch)'
        required: true
        default: 'ADF-MyADFProject-{REPLACE-ME e.g. Feature-A}'

      # This resource group for the ADF
      RESOURCE_GROUP:
        description: 'Resource Group Name'
        required: true
        default: 'ADF-MyADFProject-{REPLACE-ME e.g. Feature-A}'

      # The Azure region to which to deploy your resources
      LOCATION:
        description: 'Azure Region'
        required: true
        default: 'EastUS2'

      # For running PowerShell and creating resources
      SUBSCRIPTION_ID:
        description: 'Azure Subscription Id'
        required: true
        default: '00000000-0000-0000-0000-000000000000'

jobs:
  #############################################################
  # This is packaging up the files from Git to the Artifacts files
  #############################################################
  Build:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # Show paths
    - name: Show paths
      run: ls -R

    # Show the environment variables for debugging
    - name: Display Environment Variable
      uses: azure/powershell@v1
      with:
        inlineScript: |
          dir env:
        azPSVersion: '3.1.0'

    # Publish Artifact: Publish: ARM-Templates
    - name: 'Publish Artifact: ARM-Templates' 
      uses: actions/upload-artifact@v2
      with:
        name: 'ARM-Templates'
        path: '${{ github.workspace }}/ARM-Templates'

    # Publish Artifact: Publish: PowerShell-Scripts
    - name: 'Publish Artifact: PowerShell-Scripts' 
      uses: actions/upload-artifact@v2
      with:
        name: 'PowerShell-Scripts'
        path: '${{ github.workspace }}/PowerShell-Scripts'

    - name: Checkout adf_publish branch
      uses: actions/checkout@v2
      with:
        ref: adf_publish

    # Show paths
    - name: Show paths
      run: ls -R

    # Publish Artifact: adf_publish files
    - name: 'Publish Artifact: adf_publish' 
      uses: actions/upload-artifact@v2
      with:
        name: 'Publish-Files'
        path: '${{ github.workspace }}/${{ github.event.inputs.ADF_PUBLISH_FOLDER }}'


        
#############################################################
# Deploy 
#############################################################
  Dev:
    needs: Build
    runs-on: ubuntu-latest

    steps:
    # Show the environment variables for debugging
    - name: Display Environment Variable
      uses: azure/powershell@v1
      with:
        inlineScript: |
          dir env:
        azPSVersion: '3.1.0'        

    # Download Artifact: ARM-Templates
    - name: 'Download Artifact: ARM-Templates' 
      uses: actions/download-artifact@v2
      with:
        name: 'ARM-Templates'
        path: ${{ github.workspace }}/ARM-Templates

    # Download Artifact:PowerShell-Scripts
    - name: 'Download Artifact: PowerShell-Scripts' 
      uses: actions/download-artifact@v2
      with:
        name: 'PowerShell-Scripts'
        path: ${{ github.workspace }}/PowerShell-Scripts

    # Download Artifact: Publish-Files
    - name: 'Download Artifact: Publish-Files' 
      uses: actions/download-artifact@v2
      with:
        name: 'Publish-Files'
        path: ${{ github.workspace }}/Publish-Files

    # Login to Azure
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # set this if you will be using PowerShell
        enable-AzPSSession: true 

    # Deploy ADF Azure Resource
    - name: Deploy ARM Template (ADF)
      uses: azure/CLI@v1
      # if: ${{ github.event.inputs.MODE == 'SKIP FOR TESTING' }}
      with:
        inlineScript: |
          az group create --location "${{ github.event.inputs.LOCATION }}" --name "${{ github.event.inputs.RESOURCE_GROUP }}"
          az deployment group create --resource-group ${{ github.event.inputs.RESOURCE_GROUP }} --template-file $GITHUB_WORKSPACE/ARM-Templates/Create-ADF-Template.json --parameters @$GITHUB_WORKSPACE/ARM-Templates/Create-ADF-Parameters.json --parameters name="${{ github.event.inputs.ADF_NAME }}"

    # ADF Pre-Deployment - Stop ADF Triggers
    - name: ADF Pre-Deployment - Stop ADF Triggers
      uses: azure/powershell@v1
      with:
        inlineScript: |
          dir env:
        azPSVersion: '3.1.0'              
